//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Attendee
    {
        public int attendeeId { get; set; }
        public int eventId { get; set; }
    
        public virtual Event_Details Event_Details { get; set; }
    }
}
