//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event_Details()
        {
            this.Event_Attendee = new HashSet<Event_Attendee>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public int eventId { get; set; }
        public int categoryId { get; set; }
        public string eventName { get; set; }
        public string eventDescription { get; set; }
        public string venue { get; set; }
        public System.DateTime eventDate { get; set; }
        public int organizerId { get; set; }
        public decimal ticketPrice { get; set; }
        public int totalSeats { get; set; }
        public string imagePath { get; set; }
        public string City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_Attendee> Event_Attendee { get; set; }
        public virtual Event_Category Event_Category { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
