//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentId { get; set; }
        public int bookingId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string status { get; set; }
        public string paymentMode { get; set; }
        public decimal amount { get; set; }
        public string cardNumer { get; set; }
        public string cardType { get; set; }
        public string expiryDate { get; set; }
        public Nullable<int> cvv { get; set; }
    }
}
